

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: learn-ingress
#   namespace: myapp
# spec:
#   rules:
#     - host: learn.io
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: myapp-service
#                 port:
#                   number: 8080

